# Generated by Django 4.1.4 on 2023-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotamain', '0002_category_match_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категорії', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Матчі', 'verbose_name_plural': 'Матчі'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
